
default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs unit tests"
  lane :run_unit_tests do
    scan(
      scheme: "RedditUnitTests",
      derived_data_path: ENV["DERIVED_DATA_PATH"],
      destination: ENV["IPHONE_12"]
    )
  end

  lane :run_ui_tests do
    scan(
      scheme: "RedditUITests",
      derived_data_path: ENV["DERIVED_DATA_PATH"],
      destination: ENV["IPHONE_12"]
    )
  end
end
